CREATE TYPE user_role AS ENUM (
    'ADMIN',
    'MODERATOR',
    'WRITER',
    'READER',
    'AUTHORIZED'
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING(30) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
    password CHARACTER(64) NOT NULL,
    role user_role NOT NULL
);
