on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16.3
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: pe_project
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'

            -   name: Build
                run: |
                    export db_host=database
                    cp app.properties.example app.properties
                    chmod +x ./gradlew
                    ./gradlew build -x test
            -   name: Test
                run: ./gradlew test

            -   name: Upload build artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: application.jar
                    path: build/libs/*-all.jar
                    overwrite: true
